dist: bionic
language: go

before_install:
  - curl -O https://download.joinself.com/olm/libself-olm_0.1.14_amd64.deb
  - curl -O https://download.joinself.com/omemo/libself-omemo_0.1.1_amd64.deb
  - sudo apt update
  - sudo apt install libsodium-dev
  - sudo apt install ./libself-olm_0.1.14_amd64.deb
  - sudo apt install ./libself-omemo_0.1.1_amd64.deb

go:
  - "1.13"
  - master
